# this is just used to store the warp points, you can edit them if you want or even manually put one, 
# just make sure to follow the right structure and use the right coords (dont want to warp into dirt!)