name: WarpDeDorp
main: games.skweekychair.warpdedorp.WarpDDPlugin
version: 1.0
api-version: 1.16
commands:
   warp:
      description: warp 2 location
      usage: /<command> [location]
      permission: warpdedorp.warp
   addwarp:
      description: add a warp location
      usage: /<command> [name]
      permission: warpdedorp.addwarp
permissions:
   warpdedorp.warp:
      default: true
   warpdedorp.addwarp:
      default: true