name: WarpDeDorp
main: games.skweekychair.warpdedorp.WarpDDPlugin
version: 1.0
api-version: 1.16
commands:
   warp:
      description: warp 2 location
      usage: /<command> [name]
      permission: warpdedorp.warp
   addwarp:
      description: add a warp location
      usage: /<command> [name] (worldname xcord ycord zcord) (yaw pitch)
      permission: warpdedorp.addwarp
   delwarp:
      description: remove warp point
      usage: /<command> [name]
      permission: warpdedorp.delwarp
permissions:
   warpdedorp.warp:
      default: true
   warpdedorp.addwarp:
      default: op
   warpdedorp.delwarp:
      default: op